### ISSUE TITLE
How to maintain aspect ratio

### ISSUE THREAD

**Issue by adnanmayo** [matriphe/laravel-imageupload#11]
Hi ,

This is realy a nice package which handles images very well. i want to maintain aspect ratio of images is this possible with this package?

**Comment by matriphe** [comment]
to maintain aspect ratio, just set in the config, set the third parameter in config to `false`

``` php
'dimensions' => array(
     'square50' => array(50, 50, true),
   ),
```

it will automatically set the max width or max height to 50 px.
