### ISSUE TITLE
Laravel 5.4 Bug. Call to undefined method Illuminate\Foundation\Application::share() 

### ISSUE THREAD

**Issue by samarhaider** [matriphe/laravel-imageupload#14]
Steps Reproducing the bug:

1. Start Fresh Installation Laravel 5.4
2. Install Package 

> composer require "matriphe/imageupload"

3. Add Providers to Config/App.php
4. Run PHP Artisan in console. 

[ERROR] Error Message:

> [Symfony\Component\Debug\Exception\FatalThrowableError]
> Call to undefined method Illuminate\Foundation\Application::share()

**Comment by glmdev** [comment]
Make sure you are using the dev-master version. Currently the dev-master branch is the only one that contains the patch for this bug ( [PR](https://github.com/matriphe/laravel-imageupload/pull/13) ). You can do this with:

`composer require matriphe/imageupload:dev-master`

**Comment by glmdev** [comment]
@matriphe This could be fixed with a version release.

**Comment by matriphe** [comment]
Hi,

Thanks for the issue. The PR #13 should fix the problem. I will tag it to new version so you can use it normally.

Sorry for the late response. :)

**Comment by matriphe** [comment]
@glmdev yes.. I will release the new version this weekend.

**Comment by matriphe** [comment]
just released new version. simply run `composer update` or force to use 5.4 version by changing in the `composer.json` file.
