### ISSUE TITLE
$newfilename not working for rename!

### ISSUE THREAD

**Issue by mramirghafari** [matriphe/laravel-imageupload#16]
hi
i want to rename exist files but my code not working! 
Imageupload::upload($filesource, $newfilename, $dir) =>
$name is new name but it doesnt work:  :(  
`$data['result'] = Imageupload::upload($request->file('file'),$name,'/3');`
please help me. its my code:

```php
if ($request->hasFile('file')) {

            echo $filename = $_SERVER['DOCUMENT_ROOT'].'/tebray/files/3/'.$request->file->getClientOriginalName();
           
            if (file_exists($filename)) {

                $orgname =  $request->file->getClientOriginalName();
                $temp = explode(".", $orgname);
                $name = $temp[0].'-c'. '.' . end($temp);
                echo "exist: ".$name;
            }else {
                $name =  $request->file->getClientOriginalName();
                echo "no exist: ".$name;
            }


            $data['result'] = Imageupload::upload($request->file('file'),$name,'/3');
        }

   ```

**Comment by mramirghafari** [comment]
@matriphe please help me :(

**Comment by matriphe** [comment]
Can you give me more detail. What is not working? The file is not renamed? The file is not uploaded? What Laravel version do you use?

**Comment by mramirghafari** [comment]
thanks for responsibilty,

files were uploaded, but not renamed

new files were overriding, which is solved thrugh config by changing newfilename value to custom
