### ISSUE TITLE
cannot upload images for no reason

### ISSUE THREAD

**Issue by loganfreeman** [matriphe/laravel-imageupload#17]
I used your awesome upload module to upload images.

composer.json require

```
"matriphe/imageupload": "5.*"
```

form 

```
<input type="file" class="form-control" name="image" accept="image/gif, image/jpeg, image/png">
```

controller

```
if ($request->hasFile('image')) {
            Log::debug('Upload images: '.$post->id);
            Imageupload::upload($request->file('image'), $post->id);
        }
```

config

```
'newfilename' => 'custom',
```

However I couldn't upload the following image:

[image](http://www.discoveralta.com/wp-content/uploads/2011/07/Wildflowers-with-mountain-9.jpg)

I don't know why.

I can upload jpeg, jpg, png, gif files without problems.

weird

**Comment by matriphe** [comment]
I downloaded your image, and uploaded it successfully on my laptop. Is there any error or exception thrown?

Have you set the max upload size in the `php.ini`?

What version of Laravel do you use?

**Comment by ultrono** [comment]
Do you have ```enctype="multipart/form-data"``` on your form?

**Comment by loganfreeman** [comment]
I think maybe there is an upload size limit on it. Thanks
