### ISSUE TITLE
Resized images are not saved

### ISSUE THREAD

**Issue by jbolter** [matriphe/laravel-imageupload#19]
After updating to the latest library (we were on a version that was a few months old) we noticed that resized images are not being saved.  Only the original was being saved even and nothing had changed in our code.

Traced this to no "save()" call in the resized image function.

Opened a PR to fix this https://github.com/matriphe/laravel-imageupload/pull/18

Let me know if there is a something wrong on my end and if resized images are being saved for others.  Thanks!

**Comment by matriphe** [comment]
Great job! thanks!
