### ISSUE TITLE
valid size and format of uploaded files

### ISSUE THREAD

**Issue by mramirghafari** [matriphe/laravel-imageupload#20]
Hi
is it possible to get valid size and format of uploaded files from config/imageupload.php? how?
otherwise how can i add it to following piece of code?

`
if (Request::hasFile('file')) {
    $result = Imageupload::upload(Request::file('file'));
}
`
for example if file is photo max upload size set to 2mb or if file is zip max upload size change to 30mb

**Comment by matriphe** [comment]
Can you be more specific, by giving more detail example?

**Comment by mramirghafari** [comment]
@matriphe 
i use following code:
`if ($request->hasFile('file') ) {
            $filename = $_SERVER['DOCUMENT_ROOT'].'/tebray/files/'.$patient_id.'/'.$request->file->getClientOriginalName();
} `

and i want to upload just .jpg .jpeg .png and .zip .rar files

I was looking for a way to upload files and no more than 2 MB in size
Can I specify it in config/imageupload.php file?
If not how to specify?

**Comment by matriphe** [comment]
Basically, this is for uploading image. so, the ZIP and RAR file will not work. By default this script will only accept images (.jpg, .png, .gif) file by detecting the mime type.

Do you mean to set the maximum upload of the file? This setting should be set in the `php.ini` (and the web server config).

**Comment by mramirghafari** [comment]
@matriphe 
I uploaded the zip file and had no problem.
I want to specify the file size via if statement. like this:

```php
if ((($_FILES["file"]["type"] == "image/gif")
|| ($_FILES["file"]["type"] == "image/jpeg")
|| ($_FILES["file"]["type"] == "image/pjpeg"))
&& ($_FILES["file"]["size"] < 20000))
  {
  if ($_FILES["file"]["error"] > 0)
    {
    echo "Return Code: " . $_FILES["file"]["error"] . "<br />";
    }
  else
    {
    echo "Upload: " . $_FILES["file"]["name"] . "<br />";
    echo "Type: " . $_FILES["file"]["type"] . "<br />";
    echo "Size: " . ($_FILES["file"]["size"] / 1024) . " Kb<br />";
    echo "Temp file: " . $_FILES["file"]["tmp_name"] . "<br />";

    if (file_exists("upload/" . $_FILES["file"]["name"]))
      {
      echo $_FILES["file"]["name"] . " already exists. ";
      }
    else
      {
      move_uploaded_file($_FILES["file"]["tmp_name"],
      "upload/" . $_FILES["file"]["name"]);
      echo "Stored in: " . "upload/" . $_FILES["file"]["name"];
      }
    }
  }
else
  {
  echo "Invalid file";
  }
```

But I do not know how to do this in this package on laravel!!

**Comment by matriphe** [comment]
I think it's easier to use Laravel's Request File method. You don't even need this package.

You can do something like this.

```php
$file = Request::file('file');

if (
    in_array($file->getClientMimeType(), ['image/gif', 'image/jpeg', 'image/pjpeg']) 
    && $file->getClientSize() < 20000
    && ! $file->getError()
    && $file->isValid()
) {
    // Upload file to path
    $file->move('upload/', $file->getClientOriginalName());
    echo 'Uploaded.';
} else {
    echo $file->getError();
}
```
