### ISSUE TITLE
getting error on file upload

### ISSUE THREAD

**Issue by adnanmayo** [matriphe/laravel-imageupload#22]
Hi i am trying to upload file to public folder. there is no AWS or S3 storage still i am getting this error 
Class 'League\Flysystem\AwsS3v3\AwsS3Adapter' not found
--
 

how this can be fixed?

Laravel 5.4, PHP 7.1

**Comment by ghost** [comment]
I think you need to disable s3 on config file like this:
's3_enabled' => false
