### ISSUE TITLE
Last folder always ignored

### ISSUE THREAD

**Issue by ghost** [matriphe/laravel-imageupload#23]
Hello , when using 

> Imageupload::upload($a, $b, $path)

The $path always ignores the last folder 

Example : $path = "profiles/profile-test/" will save the image to profiles folder , if you add "/anything/" then it will save to /profiles/profile-test/.

**Comment by matriphe** [comment]
Can you give me the config file yo use? I think you should set the `suffix` on the configuration to `false` so the image will be uploaded to the path.
