### ISSUE TITLE
Non-static method upload() should not be called statically

### ISSUE THREAD

**Issue by syedarifiqbal** [matriphe/laravel-imageupload#24]
I am trying to upload using this package but getting this error.

`**Non-static method Matriphe\Imageupload\Imageupload::upload() should not be called statically**`

i check the core class **Imageupload** and i didn't find any static method while in the documentation every example used as static method.

> **Note:** I am using laravel 5.6

**Comment by matriphe** [comment]
Hello there. 

Have you load the facade from the source? Please make sure you've added this line in the `config/app.php`:

```php
Imageupload' => Matriphe\Imageupload\ImageuploadFacade::class,
```

In the source, you should use the facade instead of the library.

```php

use Imageupload;
...
Imageupload::upload();

```

**Comment by syedarifiqbal** [comment]
But i notice in document there is instruction to no need to add facade for 5.5. and i am in 5.6. do i still need this to add in config/app.php

**Comment by matriphe** [comment]
In Laravel 5.5 or above, yes you don't need to add anything in the `config/app.php`, the package will auto register the service provider and the facade, but you still should load the facade manually in the source.

```php
use Imageupload;
```

Instead of

```php
use Matriphe\Imageupload\Imageupload
```

If you don't want to use facade, just create the object, and use the regular method.

````php
use Matriphe\Imageupload\Imageupload;

$imageupload = new Imageupload;
$imageupload->upload()

````

**Comment by syedarifiqbal** [comment]
Okay it works.  Thank you.

the problem was that i use 

`
use Matriphe\Imageupload\Imageupload
`

i replace with

`use Matriphe\Imageupload\Imageupload`

and All good to go.
