### ISSUE TITLE
Composer Requirement for Laravel 5.1

### ISSUE THREAD

**Issue by lapubell** [matriphe/laravel-imageupload#3]
Can you please update the library composer requirements for illuminate/support up to 5.1?

Not sure if it's tested, but supposedly 5.1 isn't a breaking release. It's LTS too, so it'd be worth it to make the library for that version. Thanks for the image uploading goodness!

**Comment by matriphe** [comment]
Hello @lapubell,
Yes, I do have plan to use it in Laravel 5.1. And feel free if you want to make pull request.

**Comment by matriphe** [comment]
Hi @lapubell, just updated the library to support Laravel 5.1. Just check the docs. Thanks!
