### ISSUE TITLE
File  name chines upload succcess ,  access http   file not fount 404

### ISSUE THREAD

**Issue by apsana** [matriphe/laravel-imageupload#5]

**Comment by matriphe** [comment]
Can you provide more info? File example?

**Comment by apsana** [comment]
Before file name is like QQ_截图_20155455465556_square50.png

after uploaded to  server it became like QQ鎴浘20151016185605.png
And can not access .

**Comment by matriphe** [comment]
What kind of server do you have? Is the permission set correctly? Can you attache the example file, so I can check it?

**Comment by apsana** [comment]
windows  file name like 电脑知识.jpg   upload then itis changed  ,you try  any file file name  chines

**Comment by matriphe** [comment]
can not reproduce
