### ISSUE TITLE
Check if it is an image

### ISSUE THREAD

**Issue by TheTechnoMan** [matriphe/laravel-imageupload#7]
Hey,

grat package, it is however coming with a big security hole. You need to implement a check that makes sure that it is indeed an image, if not reject it, don't even store it.

Best regards

**Comment by matriphe** [comment]
Thank you for your suggestion. Will check it ASAP.

-- 
Muhammad Zamroni
Sent with Airmail

On 2 Februari 2016 at 00.05.27, TheTechnoMan (notifications@github.com) wrote:

Hey,

grat package, it is however coming with a big security hole. You need to implement a check that makes sure that it is indeed an image, if not reject it, don't even store it.

Best regards

**Comment by TheTechnoMan** [comment]
Here's the code I implemented:

```
if(isset($_FILES['image'])) {
            $info = getimagesize($_FILES['image']['tmp_name']);
            if ($info === FALSE) {
                $imageError = true;
            }

            if (($info[2] !== IMAGETYPE_GIF) && ($info[2] !== IMAGETYPE_JPEG) && ($info[2] !== IMAGETYPE_PNG)) {
                $imageError = true;
            }

            if(isset($imageError)) {
                return redirect()->back();
            }
        }
```

**Comment by matriphe** [comment]
It willl be great if you could make a PR

-- 
Muhammad Zamroni
Sent with Airmail

On 2 Februari 2016 at 00.58.14, TheTechnoMan (notifications@github.com) wrote:

Here's the code I implemented:

`$info = getimagesize($_FILES['image']['tmp_name']);
            if ($info === FALSE) {
                $imageError = true;
            }

```
        if (($info[2] !== IMAGETYPE_GIF) && ($info[2] !== IMAGETYPE_JPEG) && ($info[2] !== IMAGETYPE_PNG)) {
            $imageError = true;
        }
```

If isset $imageError then reject :)
