### ISSUE TITLE
Laravel 5.2

### ISSUE THREAD

**Issue by iemand002** [matriphe/laravel-imageupload#8]
Laravel 5.2 is now the latest.
Could you please update the composer file?

Thank you!

**Comment by strikermdd** [comment]
Yes. Please update this package to work with Laravel 5.2, i´m using in a project of mine, but can´t use it right now because this version restriction.

Thanks.

**Comment by matriphe** [comment]
Hey guys, sorry for the very late respond.

I just make the library to support Laravel 5.2 since I started to use it for my next project.
