### ISSUE TITLE
FileNotFoundException

### ISSUE THREAD

**Issue by beshambher** [matriphe/laravel-imageupload#9]
Does anybody knows why is this happening?

FileNotFoundException in MimeTypeGuesser.php line 123:
The file "" does not exist

I'm trying to upload an image with this:

<input type="file" name="image" />
.
.
.
//in PHP function
            //create new image
            if (!empty($data['image'])) {
                //var_dump($data);
                $imageUpload = Imageupload::upload($data['image'], null, 'uploads/images/');
                $data['image'] = $imageUpload['filename'];
            }
.
.
.

**Comment by matriphe** [comment]
can you share the full code and describe the steps?

**Comment by beshambher** [comment]
I apologize for this. Actually the problem was with my server the maximum file upload was set on 20 MB and I was trying to upload a file of 21 MB.

**Comment by matriphe** [comment]
Nice to hear that.
